/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockSymbolRouteImport } from './routes/stock/$symbol'
import { Route as HoldingSymbolRouteImport } from './routes/holding/$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const StockSymbolRoute = StockSymbolRouteImport.update({
  id: '/stock/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

const HoldingSymbolRoute = HoldingSymbolRouteImport.update({
  id: '/holding/$symbol',
  path: '/holding/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/holding/$symbol': typeof HoldingSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/holding/$symbol': typeof HoldingSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stock/$symbol': typeof StockSymbolRoute
  '/holding/$symbol': typeof HoldingSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stock/$symbol' | '/holding/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stock/$symbol' | '/holding/$symbol'
  id: '__root__' | '/' | '/stock/$symbol' | '/holding/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StockSymbolRoute: typeof StockSymbolRoute
  HoldingSymbolRoute: typeof HoldingSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/$symbol': {
      id: '/stock/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof StockSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holding/$symbol': {
      id: '/holding/$symbol'
      path: '/holding/$symbol'
      fullPath: '/holding/$symbol'
      preLoaderRoute: typeof HoldingSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StockSymbolRoute: StockSymbolRoute,
  HoldingSymbolRoute: HoldingSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
